apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: image-pull-secret
    data:
        .dockerconfigjson: {{ "{\"auths\": {\"registry.example.com\": {\"username\": \"example-user\", \"password\": \"a1b2c3d4e5f6\"}}}" | b64enc }}
