apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
