apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"postgres"},"name":"postgres-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgres"}},"template":{"metadata":{"labels":{"app":"postgres"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"postgres-config-map"}}],"image":"postgres:latest","name":"postgres-cotainer","ports":[{"containerPort":5432,"name":"postgres-port"}]}]}}}}
    labels:
      app: postgres
    name: postgres-deployment
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        labels:
          app: postgres
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: postgres-config-map
          image: postgres:latest
          name: postgres-cotainer
          ports:
          - containerPort: 5432
            name: postgres-port
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"default"},"spec":{"ports":[{"name":"postgres-svc-port","port":5432,"protocol":"TCP","targetPort":"postgres-port"}],"selector":{"app":"postgres"}}}
    name: postgres
    namespace: default
  spec:
    ports:
    - name: postgres-svc-port
      port: 5432
      protocol: TCP
      targetPort: postgres-port
    selector:
      app: postgres
kind: List
metadata: {}
